name: ComplexMobs
author: Amir
version: 0.8
main: complexMobs.main.ComplexMobs
description: Plugin that allows for the creation and use of complex mobs.
api-version: 1.13
commands:
    summoncomplexmob:
        description: Spawns complex mobs at the current position
        usage: /summoncomplexmob
    removeallcomplexmobs:
        description: Removes all complex mobs from the game
        usage: /removeallcomplexmobs
